#!/usr/bin/bash
sudo dnf install -y ansible-core
ansible-galaxy collection install community.general 
ansible-galaxy collection install ansible.posix
ansible-playbook $HOME/workbench/Lazy-SysAdmin/System-Setup/SysConfig.yaml